# Generated by Django 4.0.1 on 2022-11-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('cast_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(verbose_name='2022-11-11T10:41:45.956507')),
                ('updated_at', models.DateTimeField(verbose_name='2022-11-11T10:41:45.956507')),
                ('runtime', models.IntegerField()),
                ('language', models.CharField(max_length=20)),
                ('tagline', models.CharField(max_length=100)),
            ],
        ),
    ]
