# Generated by Django 4.0.1 on 2022-11-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_movie_created_at_alter_movie_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='updated_at',
            field=models.DateField(),
        ),
    ]
